Book:
  DisplayName: "인챈트 뽑기"
  CustomModelData: -1
  Lore:
    - "&a우클릭시 랜덤한 인챈트를 뽑습니다"
    - ""
    - "&a인벤토리에 공간이 없을시 현재 위치에 아이템이 드롭됩니다"

LottoEnchantBook: #format: <enchantKey>:<level>:<amount>:<weight>
  - air:1:1:100
  - mending:1:1:10
